version: '3.6'

services:
  app: 
    build: .
    ports:
      - "3000:3000" 
      - "9229:9229"
    working_dir: /usr/src/app
    command:
      - node
      - "--inspect-brk=0.0.0.0"
      - "./app.js" 
